In [1]:
import pandas as pd 
data = pd.read_csv("bengaluru_house_prices.csv")
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [2]:
data.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [3]:
data.drop(columns=["area_type","availability","society","balcony"],axis=1,inplace=True)

In [4]:
data.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [5]:
data.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

in this data set have a null values so we have to drop them

In [6]:
data.dropna(inplace=True)

In [7]:
data.duplicated().sum()

881

also drop duplicate values

In [8]:
data.drop_duplicates(inplace=True)

In [9]:
data.shape

(12365, 5)

In [10]:
data.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [11]:
data["size"] = data["size"].apply(lambda x: x.split(" ")[0]).astype(int)

In [12]:
data["size"].info()

<class 'pandas.core.series.Series'>
Index: 12365 entries, 0 to 13318
Series name: size
Non-Null Count  Dtype
--------------  -----
12365 non-null  int32
dtypes: int32(1)
memory usage: 144.9 KB

In [13]:
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [14]:
from house import logging
def clean_sqft(col):
    """
    Cleans and processes the `total_sqft` column.
    Handles ranges (e.g., '1000-1200') and non-numeric values.
    """
    try:
        tokens = col.split("-")
        if len(tokens) == 2:
            return (float(tokens[0]) + float(tokens[-1])) / 2
        return float(col)
    except ValueError:
        logging.warning(f"Non-numeric value encountered in 'total_sqft': {col}")
        return None

In [17]:
data['total_sqft'] = data['total_sqft'].apply(clean_sqft)

In [18]:
data.head()

                   location  size  total_sqft  bath   price
0  Electronic City Phase II     2      1056.0   2.0   39.07
1          Chikka Tirupathi     4      2600.0   5.0  120.00
2               Uttarahalli     3      1440.0   2.0   62.00
3        Lingadheeranahalli     3      1521.0   3.0   95.00
4                  Kothanur     2      1200.0   2.0   51.00

In [19]:
data.shape

(12365, 5)

In [23]:
data[data['total_sqft']=='None']

Empty DataFrame
Columns: [location, size, total_sqft, bath, price]
Index: []

In [20]:
data.dropna(subset=['total_sqft'])

                       location  size  total_sqft  bath   price
0      Electronic City Phase II     2      1056.0   2.0   39.07
1              Chikka Tirupathi     4      2600.0   5.0  120.00
2                   Uttarahalli     3      1440.0   2.0   62.00
3            Lingadheeranahalli     3      1521.0   3.0   95.00
4                      Kothanur     2      1200.0   2.0   51.00
...                         ...   ...         ...   ...     ...
13314         Green Glen Layout     3      1715.0   3.0  112.00
13315                Whitefield     5      3453.0   4.0  231.00
13316             Richards Town     4      3600.0   5.0  400.00
13317     Raja Rajeshwari Nagar     2      1141.0   2.0   60.00
13318           Padmanabhanagar     4      4689.0   4.0  488.00

[12319 rows x 5 columns]

aa 
def clean_sqft(col):
    tokens = col.split("-")
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[-1])) / 2
    try: 
        return float(col)
    except:
        return None

In [16]:
aa 
data['total_sqft'] = data['total_sqft'].apply(clean_sqft)

NameError: name 'aa' is not defined

In [17]:
data.head()

                   location  size  total_sqft  bath   price
0  Electronic City Phase II     2      1056.0   2.0   39.07
1          Chikka Tirupathi     4      2600.0   5.0  120.00
2               Uttarahalli     3      1440.0   2.0   62.00
3        Lingadheeranahalli     3      1521.0   3.0   95.00
4                  Kothanur     2      1200.0   2.0   51.00

In [18]:
data['location'].value_counts()

location
Whitefield               501
Sarjapur  Road           357
Electronic City          273
Thanisandra              223
Kanakpura Road           217
                        ...
Maruthi Extension          1
Okalipura                  1
Old Town                   1
Vasantapura main road      1
Abshot Layout              1
Name: count, Length: 1304, dtype: int64

In [19]:
location_status = data['location'].value_counts()
location_status

location
Whitefield               501
Sarjapur  Road           357
Electronic City          273
Thanisandra              223
Kanakpura Road           217
                        ...
Maruthi Extension          1
Okalipura                  1
Old Town                   1
Vasantapura main road      1
Abshot Layout              1
Name: count, Length: 1304, dtype: int64

In [20]:
location_less_20 = location_status[location_status < 20]
location_less_20

location
Kaggalipura              19
HRBR Layout              19
OMBR Layout              19
Choodasandra             19
Yelachenahalli           19
                         ..
Maruthi Extension         1
Okalipura                 1
Old Town                  1
Vasantapura main road     1
Abshot Layout             1
Name: count, Length: 1165, dtype: int64

In [21]:
data['location'] = data['location'].apply(lambda x:'others' if x in location_less_20 else x)

In [22]:
data.head()

                   location  size  total_sqft  bath   price
0  Electronic City Phase II     2      1056.0   2.0   39.07
1                    others     4      2600.0   5.0  120.00
2               Uttarahalli     3      1440.0   2.0   62.00
3        Lingadheeranahalli     3      1521.0   3.0   95.00
4                  Kothanur     2      1200.0   2.0   51.00

In [23]:
data.columns

Index(['location', 'size', 'total_sqft', 'bath', 'price'], dtype='object')

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,LabelEncoder,PowerTransformer,OneHotEncoder
from sklearn.pipeline import Pipeline

In [25]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import PowerTransformer, StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

# Define numerical and categorical columns
num_columns = ['size', 'total_sqft', 'bath']
cat_columns = ['location']

# Create pipelines for numerical and categorical transformations
num_pipeline = Pipeline([
    ('power', PowerTransformer(method='yeo-johnson')),
    ('scaler', StandardScaler())
])

cat_pipeline = OneHotEncoder(handle_unknown='ignore')

# Combine transformations into a ColumnTransformer
preprocess = ColumnTransformer([
    ('num', num_pipeline, num_columns),
    ('cat', cat_pipeline, cat_columns)
])

# Split data into features and target
X = data.drop(columns='price', axis=1)
y = data['price']

# Apply preprocessing to the features
X = preprocess.fit_transform(X)

# Optional: Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
from xgboost import XGBRegressor

In [27]:
xgb = XGBRegressor()

In [28]:
xgb.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [29]:
pred = xgb.predict(X_test)
from sklearn.metrics import r2_score
r2_score(pred,y_test)

0.39285038763252256

In [30]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(X_train,y_train)
pred = rfr.predict(X_test)
from sklearn.metrics import r2_score
r2_score(pred,y_test)

ValueError: Input X contains NaN.
RandomForestRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values